### PR TITLE
remove discoveryServiceUrl, update docs

### LINKED ISSUE #473: google-api-python-client updates
I'm seeing consistent errors for the Google API converters, that I think trace back to an updated internal API :

For example, when running the `GoogleSpeechAPIConverter`:

```
  File "/home/users/emdupre/miniconda3/envs/pliers/lib/python3.9/site-packages/pliers/converters/api/google.py", line 51, in _query_api
    request_obj = self.service.speech().recognize(body=request)
AttributeError: 'NoneType' object has no attribute 'speech'
```

Similarly for the `GoogleVision` APIs:

```
  File "/home/users/emdupre/miniconda3/envs/pliers/lib/python3.9/site-packages/pliers/transformers/api/google.py", line 98, in _query_api
    request_obj = self.service.images() \
AttributeError: 'NoneType' object has no attribute 'images'
```

Following [this guide](https://cloud.google.com/vision/docs/detecting-faces#vision_face_detection-python) and its accompanying [Python quickstart](https://cloud.google.com/vision/docs/detect-labels-image-client-libraries), I _believe_ that `google-api-python-client` -- while still officially supported ! -- had a [breaking change 2.0 release](https://github.com/googleapis/google-api-python-client/blob/main/UPGRADING.md#for-users-of-private-apis) which affected private APIs such as those used here.

It's unfortunately still not obvious to me how to update the calls to `google-api-python-client` within the existing library structure, but I'd guess we need to update the `build` call here:

https://github.com/PsychoinformaticsLab/pliers/blob/df432abb11eb56950ca5cc67896f61e9c21f304b/pliers/transformers/api/google.py#L49-L51

following [this comment](https://github.com/googleapis/google-api-python-client/issues/1491#issuecomment-903924253).

Alternatively, a larger update would be to move to the Google Cloud Client libraries, as recommended in the `google-api-python-client` [documentation](https://github.com/googleapis/google-api-python-client).

Any input here -- to either patch the current calls or on potential paths forward -- would be appreciated !

### PR DESCRIPTION
**Pull request by emdupre**
Closes #473.

Small documentation, `build` call updates for `google-api-python-client` usage.
This is very much a first pass ; feedback welcome !

### CODE REVIEW

**Comment by emdupre** [comment]
Thanks ! I pushed a few updates on the tests that are necessary to match the new outputs.

Currently I'm still getting a few failures:

```
(pliers) Desktop/pliers % GOOGLE_APPLICATION_CREDENTIALS='/Users/emdupre/Downloads/googleapi.json' pytest pliers/tests/extractors/api/test_google_extractors.py
==================================================================== test session starts ====================================================================
platform darwin -- Python 3.9.13, pytest-7.1.3, pluggy-1.0.0
rootdir: /Users/emdupre/Desktop/pliers, configfile: pytest.ini
collected 21 items                                                                                                                                          

pliers/tests/extractors/api/test_google_extractors.py .....F....C..F........                                                                           [100%]
```

Specifically, I'm getting a 403 error on one of [the test URLs](https://via.placeholder.com/350x150) and a KeyError on the "clock" label:

```
FAILED pliers/tests/extractors/api/test_google_extractors.py::test_google_vision_api_label_extractor - urllib.error.HTTPError: HTTP Error 403: Forbidden
FAILED pliers/tests/extractors/api/test_google_extractors.py::test_google_video_api_label_extractor - KeyError: 'clock'
``` 

I can get the latter to pass by changing `clock` to `category_technology`, but I need to check the video itself to make sure it's being labeled as that category rather than `electronics`, which seems to be the other option:

```
(Pdb) result.columns
Index(['order', 'duration', 'onset', 'object_id', 'animal', 'electronics',
       'category_technology', 'pet', 'category_animal', 'kitten',
       'category_cat', 'whiskers', 'cat', 'category_pet'],
      dtype='object')
```

**Comment by adelavega** [comment]
I think I fixed your issue in the general test fix. Hopefully tests pass and we can merge!

**Comment by adelavega** [comment]
Tests passing! @emdupre can you confirm this is ready to merge?

**Comment by emdupre** [comment]
This is ready on my side, thanks !!!

**Pull request merged**
