### PR TITLE
[CI] Build docker image with github actions.

### PR DESCRIPTION
**Pull request by jdkent**
using github actions to build/distribute docker image

`secrets.CR_PAT` needs to be created by someone with admin privileges.
It's a personal access token, [with package permissions](https://docs.github.com/en/packages/learn-github-packages/about-github-packages#authenticating-to-github-packages), I can do it (if you think I _should_ have admin access, hopefully to just this repository, but maybe need someone that is admin to the organization).

### CODE REVIEW

**Comment by jdkent** [comment]
finally got it passing, for some reason I cannot run the `pliers/tests/extractors/test_model_extractors.py` tests, (it times out), but should be ready for review otherwise @adelavega

**Comment by adelavega** [comment]
Ah, that's a common issue with the timeout. This is why in the past I had to split the tests into multiple lines. It probably runs out of RAM.

**Comment by adelavega** [comment]
Nice, looks good. Can you update the README or docs to reference how to use the Docker image?

**Comment by jdkent** [comment]
@adelavega there is a urllib error for the python tests that I'm not sure about, do you have any thought?

**Comment by jdkent** [comment]
@adelavega, I think this is finally ready, there is a soft limit of 14GB of storage on the runner, so I had to delete some very large unused files on the virtual machine so I could build the very large pliers image.

**Comment by jdkent** [comment]
@adelavega, does this pull request look okay? once merged, it should fix the broken tests in #454

**Review by adelavega — APPROVED** [review]
Looks excellent. Let's merge!

**Pull request merged**
