### PR TITLE
[FIX] access string in numpy array

### PR DESCRIPTION
**Pull request by jdkent**
looks like one of the changes in #418 [had a regression with the Google API](https://travis-ci.com/github/PsychoinformaticsLab/pliers/jobs/387471662#L1294),

This pull request aims to fix the regression.

### CODE REVIEW

**Comment by jdkent** [comment]
looks like my pull request does not have access to the same environmental variables as builds on master have resulting in some tests being skipped. Is this on purpose to ensure API call limits do not go over?

**Comment by adelavega** [comment]
Yes, the API tests are not being run on PRs. 

I usually will test these locally once I think I'm close. You could do the same if you get some Google keys (there should be a free tier in the meantime).

**Comment by jdkent** [comment]
Thanks for the clarification, [is this where I get some google keys](https://console.cloud.google.com/projectselector2/apis/credentials/serviceaccountkey)?

Always wanted to take a google on a test drive

**Comment by adelavega** [comment]
yep! just get some there and put them in the environment

**Comment by adelavega** [comment]
I tested this and it fixes the regression. Will merge, but I also noticed there's a lot more regressions w/ Google API that need to be looked into.

**Pull request merged**
